local Maze = require "main.maze"

function init(self)
    msg.post(".", "acquire_input_focus")
    msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })
    self.maze = Maze.new(50, 50, 64, 64)
    self.maze:generate()
    print("Maze generated")
    self.maze:debug_print()
end

function on_input(self, action_id, action)
    if action_id == hash("touch") and action.pressed then
        print("Touch!")
    end
end
